### ISSUE TITLE
wut

### ISSUE THREAD

**Issue by darkdarcool** [RayhanADev/BrainF-Hello-World#1]
who fricking codes in BrainF***

**Comment by RayhanADev** [comment]
Apparently me xD

**Comment by darkdarcool** [comment]
lol why do you do this to yourself

**Comment by darkdarcool** [comment]
all of that for just hello world smh

**Comment by RayhanADev** [comment]
It was completely worth it to say I can code in Brainf***.

**Comment by darkdarcool** [comment]
can you, and is it worth it

**Comment by darkdarcool** [comment]
to say to someone "Y'know, i am better than you because I can coding in brainf***"

**Comment by RayhanADev** [comment]
Entirely ;P

**Comment by darkdarcool** [comment]
hmmmm, i don't think you(or anyone) can actually code in brainf well
